# Generated by Django 4.1.2 on 2022-10-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shafts',
            fields=[
                ('ShaftId', models.AutoField(primary_key=True, serialize=False)),
                ('ShaftName', models.CharField(max_length=500)),
                ('ShaftMaterial', models.CharField(max_length=150)),
                ('ShaftColor', models.CharField(max_length=150)),
                ('ShaftDateMade', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('TipId', models.AutoField(primary_key=True, serialize=False)),
                ('TipName', models.CharField(max_length=500)),
            ],
        ),
    ]
