# Generated by Django 4.1.2 on 2022-10-13 17:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endcaps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MadeDate', models.DateTimeField(default=datetime.date.today)),
                ('MadeOf', models.CharField(max_length=150)),
                ('Color', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='MagicWands',
            fields=[
                ('magicWandId', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('pubDate', models.DateField(default=datetime.date.today)),
                ('power', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('MadeDate', models.DateTimeField(auto_now_add=True)),
                ('MadeOf', models.CharField(max_length=150)),
                ('Color', models.CharField(max_length=150)),
                ('Power', models.IntegerField()),
            ],
            options={
                'ordering': ['-MadeDate'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shafts',
            fields=[
                ('ShaftId', models.AutoField(primary_key=True, serialize=False)),
                ('ShaftName', models.CharField(max_length=500)),
                ('ShaftMaterial', models.CharField(max_length=150)),
                ('ShaftColor', models.CharField(max_length=150)),
                ('ShaftDateMade', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('TipId', models.AutoField(primary_key=True, serialize=False)),
                ('TipName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Topcaps',
            fields=[
                ('endcaps', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Wand.endcaps')),
                ('SerialNumber', models.IntegerField(default=123456789)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('OwnerId', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(default='FirstName', max_length=250)),
                ('LastName', models.CharField(default='LastName', max_length=250)),
                ('MagicWand', models.ManyToManyField(to='Wand.magicwands')),
            ],
        ),
        migrations.CreateModel(
            name='Handles',
            fields=[
                ('HandleId', models.AutoField(primary_key=True, serialize=False)),
                ('MadeDate', models.DateField()),
                ('MadeOf', models.CharField(max_length=150)),
                ('Color', models.CharField(max_length=150)),
                ('AssociatedWand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Wand.magicwands')),
            ],
        ),
    ]
